apiVersion: scaffold/v1beta2
kind: Config
build: 
  local: 
    push: false
  artifacts: 
    - image: lukegartland/multi-client
      context: client 
      docker: 
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "src/**/*.js"
            dest: .
          - src: "src/**/*.css"
            dest: .
          - src: "src/**/*.html"
            dest: .
deploy: 
  kubectl: 
    manifests: 
      - k8s/client-deployment.yaml